FROM node:14-buster as builder
WORKDIR /app
COPY package*.json /app/
RUN npm install
RUN npm run build

FROM nginx:1.20-alpine
WORKDIR /app
COPY COPY --from=/app/dist ./
COPY deploy/www.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
